



header_pages:
  - index.md 
  - about.md

footer: '<a href="https://twitter.com/cryptt1d">twitter</a>'

style: dark
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
