



header_pages:
  - index.md 
  - about.md
  - etc.md

footer: ' ______     ______     ______   ______   _____    
          /\  ___\   /\  == \   /\  == \ /\__  _\ /\  __-.  
          \ \ \____  \ \  __<   \ \  _-/ \/_/\ \/ \ \ \/\ \ 
           \ \_____\  \ \_\ \_\  \ \_\      \ \_\  \ \____- 
            \/_____/   \/_/ /_/   \/_/       \/_/   \/____/ 
                                                            '

style: dark
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
